# Generated by Django 3.1.3 on 2020-11-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
    ]
