# Generated by Django 3.1.3 on 2020-11-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_likes'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='users', to='news.News'),
        ),
    ]
