# Generated by Django 3.1.3 on 2020-11-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('account', '0002_auto_20201107_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='like',
            field=models.ManyToManyField(to='news.News'),
        ),
        migrations.AlterField(
            model_name='account',
            name='favourite',
            field=models.ManyToManyField(to='news.Category'),
        ),
    ]
