# Generated by Django 3.1.3 on 2020-11-16 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201108_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='like',
            new_name='likes',
        ),
    ]
