# Generated by Django 3.1.3 on 2020-11-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_likes'),
        ('account', '0006_auto_20201116_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='favourite',
            field=models.ManyToManyField(blank=True, to='news.Category'),
        ),
        migrations.AlterField(
            model_name='account',
            name='likes',
            field=models.ManyToManyField(related_name='users', to='news.News'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(default='profilePic/pp.png', upload_to='profilePic/'),
        ),
    ]
