# Generated by Django 3.1.3 on 2020-11-15 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201109_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date']},
        ),
    ]
