# Generated by Django 3.1.3 on 2020-11-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201108_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(default='pp.png', upload_to=''),
        ),
    ]
