# Generated by Django 3.1.3 on 2020-11-24 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('publish',)},
        ),
    ]
